version: '3'

tasks:
  proto:
    - protoc --go_out=. --plugin=protoc-gen-go=$(which protoc-gen-go) --go_opt=paths=source_relative --go-grpc_out=. --plugin=protoc-gen-go-grpc=$(which protoc-gen-go-grpc) --go-grpc_opt=paths=source_relative proto/chat.proto
    
  proto1:
    - protoc --go_out=pb --plugin=protoc-gen-go=$(which protoc-gen-go) --go_opt=paths=source_relative
       --go-grpc_out=pb --plugin=protoc-gen-go-grpc=$(which protoc-gen-go-grpc) --go-grpc_opt=paths=source_relative
       proto/*.proto

  proto2:
    - protoc --go_out=./pb --go_opt=module=example.com/pb --plugin=protoc-gen-go=$(which protoc-gen-go) --go-grpc_out=./pb --go-grpc_opt=module=example.com/pb --plugin=protoc-gen-go-grpc=$(which protoc-gen-go-grpc) proto/chat.proto     
  
  ptc:
    - protoc --proto_path=proto proto/*.proto --go_out=plugins=grpc:pb   

  buf:
    - buf generate  
